services:
  postgres:
    image: postgres
    container_name: stripe-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stripe_payments
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: